"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import Cursor from "@/components/shared/Cursor/Cursor";
import { AnimatePresence } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rabby Khan - MERN Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresence>
        <body className={`${inter.className} bg-accent`}>
          <Cursor />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </body>
      </AnimatePresence>
    </html>
  );
}
